package com.security.alarm.repository;

import com.security.alarm.entity.ReportLog;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

public interface ReportLogRepository extends JpaRepository<ReportLog, Long> {

    Optional<ReportLog> findByReportId(String reportId);

    List<ReportLog> findByGeneratedByOrderByGeneratedAtDesc(String generatedBy);

    List<ReportLog> findByCompanyIdOrderByGeneratedAtDesc(Long companyId);

    List<ReportLog> findAllByOrderByGeneratedAtDesc();

    @Query("SELECT r FROM ReportLog r WHERE r.isAutoGenerated = true AND r.generatedAt < :cutoff")
    List<ReportLog> findAutoGeneratedOlderThan(@Param("cutoff") LocalDateTime cutoff);

    long countByCompanyId(Long companyId);
}