package com.security.alarm.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.time.LocalDate;

@Entity
@Table(name = "report_logs")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ReportLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "report_id", unique = true, nullable = false, length = 100)
    private String reportId;

    @Column(name = "generated_by", nullable = false, length = 50)
    private String generatedBy;

    @Column(name = "generated_at", nullable = false)
    private LocalDateTime generatedAt = LocalDateTime.now();

    @Column(name = "report_type", nullable = false, length = 10)
    private String reportType; // PDF, EXCEL

    @Column(name = "date_from")
    private LocalDate dateFrom;

    @Column(name = "date_to")
    private LocalDate dateTo;

    @Column(name = "total_alerts")
    private Integer totalAlerts = 0;

    @Column(name = "file_name", length = 255)
    private String fileName;

    @Column(name = "file_size")
    private Long fileSize;

    @Column(name = "file_path", length = 500)
    private String filePath;

    @Lob
    @Column(name = "file_content")
    private byte[] fileContent;

    @Column(name = "status", length = 20)
    private String status = "ACTIVE"; // ACTIVE, ARCHIVED, DELETED

    @Column(name = "company_id")
    private Long companyId;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = false;

    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();
}